[workspace]
members = ["libmemetendo", "memetendo", "web-memetendo"]
default-members = ["libmemetendo", "memetendo"]
resolver = "2"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
lto = true

[profile.release-dev]
inherits = "release"
debug = true
